name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'  # Update every 30 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2  # Checkout the repository
      - name: Update README with activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Access token for authentication
          README_TITLE: "<span style='color: #800080;'>Python Repository 📦🐍</span>\n## <span style='color: #800080;'>Stats 📈</span>"  # Custom title
          README_BODY: |
            <p align="center">
              <!-- Placeholder for the most used languages but showing nothing -->
              <img width="0%" height="0px" src="https://github-readme-stats.vercel.app/api/top-langs?username=Newby19&show_icons=true&theme=radical&title_color=000000&text_color=000000&bg_color=ff1493&locale=en&layout=compact&hide_border=true" alt="Newby19" />
              
              <!-- Display overall GitHub stats -->
              <img width="48%" src="https://github-readme-stats.vercel.app/api?username=Newby19&show_icons=true&theme=radical&title_color=000000&text_color=000000&bg_color=ff1493&locale=en&hide_border=true" alt="Newby19" />
              
              <!-- GitHub streak stats for engagement -->
              <img width="48%" src="https://github-readme-streak-stats.herokuapp.com/?user=Newby19&theme=radical&hide_border=true" alt="Newby19" />
            </p>
